const comments = [
	"The key to more success is to get a massage once a week, very important, major key, cloth talk. Life is what you make it, so let’s make it. Stay focused. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. In life there will be road blocks but we will over come it. You see that bamboo behind me though, you see that bamboo? Ain’t nothin’ like bamboo. Bless up. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth.",
	"They will try to close the door on you, just open it. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Bless up. Don’t ever play yourself. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. They don’t want us to eat. The weather is amazing, walk with me through the pathway of more success. Take this journey with me, Lion!",
	"Let’s see what Chef Dee got that they don’t want us to eat. Don’t ever play yourself. Hammock talk come soon. Eliptical talk. They never said winning was easy. Some people can’t handle success, I can. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started.",
	"Surround yourself with angels. They don’t want us to win. Cloth talk. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Special cloth alert. Stay focused. Fan luv. Let’s see what Chef Dee got that they don’t want us to eat. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. It’s important to use cocoa butter. It’s the key to more success, why not live smooth? Why live rough? Lion! Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started.",
	"They don’t want us to win. The key is to enjoy life, because they don’t want you to enjoy life. I promise you, they don’t want you to jetski, they don’t want you to smile. Special cloth alert. Find peace, life is like a water fall, you’ve gotta flow. Bless up. The key to success is to keep your head above the water, never give up. We don’t see them, we will never see them.",
	"I’m up to something. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Another one. The key is to drink coconut, fresh coconut, trust me.",
	"Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Lion! Look at the sunset, life is amazing, life is beautiful, life is what you make it. The key is to drink coconut, fresh coconut, trust me. Lion! You see that bamboo behind me though, you see that bamboo? Ain’t nothin’ like bamboo. Bless up. You see the hedges, how I got it shaped up? It’s important to shape up your hedges, it’s like getting a haircut, stay fresh.",
	"Life is what you make it, so let’s make it. The key is to drink coconut, fresh coconut, trust me. Eliptical talk. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. We the best. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. The key is to enjoy life, because they don’t want you to enjoy life. I promise you, they don’t want you to jetski, they don’t want you to smile.",
	"Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm.",
	"You do know, you do know that they don’t want you to have lunch. I’m keeping it real with you, so what you going do is have lunch. Find peace, life is like a water fall, you’ve gotta flow. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed.",
];

export const Comment = (props) => {
	const id = props.id % 10;
	return comments[id];
};
